// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axjxfbttgfzycgfobpdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4anhmYnR0Z2Z6eWNnZm9icGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDM5MzUsImV4cCI6MjA2ODIxOTkzNX0.8EQKX0ZCDrNP86dzrKdoiB8o15DRaTVsymvFNVSsT0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});